# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DevPost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevPost
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Material design pods
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/Dialogs'

pod 'ProgressHUD'
end
